services:
  - type: web
    name: sonix
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/Code-the-Dream-School/l-group-practicum-team6
    branch: dev
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/v1/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "24"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_LIFETIME
        value: 1d
      - key: CLIENT_URL
        sync: false
      - key: VITE_API_BASE_URL
        value: ""
      - key: VITE_PUBLIC_APP_NAME
        value: Sonix
